task:
  name: RoK4
  physics_engine: physx
  env:
    numEnvs: ${resolve_default:4096,${...num_envs}}
    numObservations: 56
    numJointActions: 13
    numActions: 17
    envSpacing: 1.0
    enableDebugVis: false
    terrain:
      terrainType: plane
      staticFriction: 1.0
      dynamicFriction: 1.0
      restitution: 0.0
      curriculum: true
      maxInitMapLevel: 0
      mapLength: 8.0
      mapWidth: 8.0
      numLevels: 10
      numTerrains: 20
      terrainProportions:
      - 0.1
      - 0.1
      - 0.35
      - 0.25
      - 0.2
      slopeTreshold: 0.5
    baseInitState:
      pos:
      - 0.0442
      - 0
      - 0.95268
      rot:
      - 0.0
      - 0.0
      - 0.0
      - 1.0
      vLinear:
      - 0.0
      - 0.0
      - 0.0
      vAngular:
      - 0.0
      - 0.0
      - 0.0
    randomCommandVelocityRanges:
      linear_x:
      - -0.3
      - 0.7
      linear_y:
      - -0.3
      - 0.3
      yaw:
      - -0.8
      - 0.8
    EnvsNumRanges:
      stand_env_range: 200
      only_plus_x_envs_range: 200
      only_minus_x_envs_range: 200
      only_plus_y_envs_range: 200
      only_minus_y_envs_range: 200
      only_plus_yaw_envs_range: 200
      only_minus_yaw_envs_range: 200
      plus_x_plus_yaw_envs_range: 200
      plus_x_minus_yaw_envs_range: 200
      minus_x_plus_yaw_envs_range: 200
      minus_x_minus_yaw_envs_range: 200
    control:
      Kp:
      - 75.0
      - 75.0
      - 150.0
      - 150.0
      - 90.0
      - 90.0
      - 75.0
      - 75.0
      - 150.0
      - 150.0
      - 90.0
      - 90.0
      - 75.0
      Kd:
      - 2.5
      - 2.5
      - 5.0
      - 5.0
      - 3.0
      - 3.0
      - 2.5
      - 2.5
      - 5.0
      - 5.0
      - 3.0
      - 3.0
      - 2.5
      actionScale: 0.5
      decimation: 4
    dof_properties:
      torque_limits:
      - 150.0
      - 150.0
      - 300.0
      - 480.0
      - 180.0
      - 180.0
      - 150.0
      - 150.0
      - 300.0
      - 480.0
      - 180.0
      - 180.0
      - 150.0
      damping:
      - 0.250538652440252
      - 0.250538652440252
      - 0.50107730488
      - 0.50107730488
      - 0.130617712993805
      - 0.130617712993805
      - 0.250538652440252
      - 0.250538652440252
      - 0.50107730488
      - 0.50107730488
      - 0.130617712993805
      - 0.130617712993805
      - 0.250538652440252
      friction:
      - 0.226537899603487
      - 0.226537899603487
      - 0.4530757992
      - 3.39806849405
      - 1.79822954112
      - 1.79822954112
      - 0.226537899603487
      - 0.226537899603487
      - 0.4530757992
      - 3.39806849405
      - 1.79822954112
      - 1.79822954112
      - 0.226537899603487
      armature:
      - 0.087396415395941
      - 0.087396415395941
      - 0.17479283079
      - 0.17479283079
      - 0.084040769086151
      - 0.084040769086151
      - 0.087396415395941
      - 0.087396415395941
      - 0.17479283079
      - 0.17479283079
      - 0.084040769086151
      - 0.084040769086151
      - 0.087396415395941
    defaultJointAngles:
      L_Hip_Yaw_Joint: -0.0
      L_Hip_Roll_Joint: -0.0
      L_Hip_Pitch_Joint: -0.29670597283
      L_Knee_Pitch_Joint: 0.72954762733
      L_Ankle_Pitch_Joint: -0.43284165449
      L_Ankle_Roll_Joint: -0.0
      R_Hip_Yaw_Joint: -0.0
      R_Hip_Roll_Joint: -0.0
      R_Hip_Pitch_Joint: -0.29670597283
      R_Knee_Pitch_Joint: 0.72954762733
      R_Ankle_Pitch_Joint: -0.43284165449
      R_Ankle_Roll_Joint: -0.0
      Torso_Yaw_Joint: 0.0
    urdfAsset:
      file: urdf/rok4/urdf/rok4_train.urdf
      test_file: urdf/rok4/urdf/rok4_train.urdf
      footName: Foot
      kneeName: Thigh
      calfName: Calf
      collapseFixedJoints: false
      fixBaseLink: false
      defaultDofDriveMode: 4
    learn:
      allowKneeContacts: true
      rew_scales:
        terminalReward: 0.0
        linearVelocityXYRewardScale: 1.5
        angularVelocityZRewardScale: 0.75
        feetAirTimeRewardScale: 0.0
      pen_scales:
        linearVelocityZRewardScale: -0.05
        angularVelocityXYRewardScale: -0.005
        comHeight: -0.0
        comSupport: -0.0
        comVelZ: -0.0
        baseHeightRewardScale: -2.5
        baseOrientation: -5.0
        swingStancePhase: -0.5
        footHeight: -0.275
        footSlip: -0.025
        footGapY: -0.3
        legGapY: -0.2
        footGapXStanding: -0.05
        hipYaw: -0.025
        hipRoll: -0.025
        ankleRoll: -0.05
        kneeCollisionRewardScale: -0.1
        calfCollisionRewardScale: -0.1
        jumpPenalty: -0.15
        dofLimit: -5.0
        actionLimit: -0.001
        dofVelLimit: -0.001
        torqueRewardScale: -2.0e-07
        jointAccRewardScale: -5.0e-05
        actionRateRewardScale: -0.0005
        actionSmoothness2RewardScale: -0.0005
        jointEnergy: -0.0
        defaultPosStanding: -0.05
        hipRewardScale: -0.0
      obs_scales:
        linearVelocityScale: 1.0
        angularVelocityScale: 0.25
        dofPositionScale: 1.0
        dofVelocityScale: 1.0
        heightMeasurementScale: 5.0
      noise:
        addNoise: true
        noiseLevel: 1.0
        dofPositionNoise: 0.01
        dofVelocityNoise: 1.5
        linearVelocityNoise: 0.1
        angularVelocityNoise: 0.2
        gravityNoise: 0.05
        heightMeasurementNoise: 0.06
      randomizeFriction: true
      frictionRange:
      - 0.5
      - 1.25
      pushRobots: true
      pushInterval_s: 15
      freezecmdInterval_s: 15
      episodeLength_s: 20
    viewer:
      refEnv: 0
      pos:
      - 0
      - 0
      - 10
      lookat:
      - 1.0
      - 1
      - 9
    enableCameraSensors: false
  sim:
    dt: 0.002
    substeps: 1
    up_axis: z
    use_gpu_pipeline: ${eq:${...pipeline},"gpu"}
    gravity:
    - 0.0
    - 0.0
    - -9.81
    physx:
      num_threads: ${....num_threads}
      solver_type: ${....solver_type}
      use_gpu: ${contains:"cuda",${....sim_device}}
      num_position_iterations: 4
      num_velocity_iterations: 1
      contact_offset: 0.02
      rest_offset: 0.0
      bounce_threshold_velocity: 0.2
      max_depenetration_velocity: 100.0
      default_buffer_size_multiplier: 5.0
      max_gpu_contact_pairs: 8388608
      num_subscenes: ${....num_subscenes}
      contact_collection: 1
  task:
    randomize: false
train:
  params:
    seed: ${...seed}
    algo:
      name: a2c_continuous
    model:
      name: continuous_a2c_logstd
    network:
      name: actor_critic
      separate: true
      space:
        continuous:
          mu_activation: None
          sigma_activation: None
          mu_init:
            name: default
          sigma_init:
            name: const_initializer
            val: 0.0
          fixed_sigma: true
      mlp:
        units:
        - 512
        - 256
        - 128
        activation: elu
        d2rl: false
        initializer:
          name: default
        regularizer:
          name: None
    load_checkpoint: ${if:${...checkpoint},True,False}
    load_path: ${...checkpoint}
    config:
      name: ${resolve_default:RoK4,${....experiment}}
      full_experiment_name: ${.name}
      env_name: rlgpu
      ppo: true
      multi_gpu: ${....multi_gpu}
      mixed_precision: true
      normalize_input: true
      normalize_value: true
      normalize_advantage: true
      value_bootstrap: true
      clip_actions: true
      num_actors: ${....task.env.numEnvs}
      reward_shaper:
        scale_value: 1.0
      gamma: 0.99
      tau: 0.95
      e_clip: 0.2
      entropy_coef: 0.001
      learning_rate: 0.0003
      lr_schedule: adaptive
      kl_threshold: 0.008
      truncate_grads: true
      grad_norm: 1.0
      horizon_length: 24
      minibatch_size: 16384
      mini_epochs: 5
      critic_coef: 2
      clip_value: true
      seq_len: 4
      bounds_loss_coef: 0.001
      max_epochs: ${resolve_default:50000,${....max_iterations}}
      save_best_after: 100
      score_to_win: 20000
      save_frequency: 50
      print_stats: true
pbt:
  enabled: false
task_name: ${task.name}
experiment: ''
num_envs: ''
seed: 42
torch_deterministic: false
max_iterations: ''
physics_engine: physx
pipeline: gpu
sim_device: cuda:0
rl_device: cuda:0
graphics_device_id: 0
num_threads: 4
solver_type: 1
num_subscenes: 4
test: false
checkpoint: ''
sigma: ''
multi_gpu: false
wandb_activate: false
wandb_group: ''
wandb_name: ${train.params.config.name}
wandb_entity: ''
wandb_project: isaacgymenvs
wandb_tags: []
wandb_logcode_dir: ''
capture_video: false
capture_video_freq: 1464
capture_video_len: 100
force_render: true
headless: false
